"""Add visual_fingerprint to Medication

Revision ID: 2b9740a37d6e
Revises: edd25771e740
Create Date: 2026-01-28 03:51:04.792986

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2b9740a37d6e'
down_revision = 'edd25771e740'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caregiver_senior', schema=None) as batch_op:
        batch_op.add_column(sa.Column('added_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.alter_column('caregiver_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('senior_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('caregiver_senior_senior_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('caregiver_senior_caregiver_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['caregiver_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['senior_id'], ['id'])
        batch_op.drop_column('is_active')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('medication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('morning', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('afternoon', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('evening', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('night', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reminder_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reminder_sound', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reminder_voice', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('custom_reminder_times', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('image_features', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('label_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reference_images', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('background_image', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('visual_fingerprint', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_trained', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('dosage',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('frequency',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('reference_image_path',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.create_index(batch_op.f('ix_medication_barcode'), ['barcode'], unique=False)
        batch_op.create_index(batch_op.f('ix_medication_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_medication_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_medication_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_medication_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_medication_user_id'), ['user_id'], unique=False)
        batch_op.drop_column('notification_time')
        batch_op.drop_column('stock_threshold')
        batch_op.drop_column('reminder_times')
        batch_op.drop_column('last_taken')
        batch_op.drop_column('is_active')
        batch_op.drop_column('pill_count')

    with op.batch_alter_table('medication_interaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medication1_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('medication2_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('recommendation', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('source', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('risk_factors', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.alter_column('severity',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('medication_interaction_med1_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('medication_interaction_med2_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'medication', ['medication1_id'], ['id'])
        batch_op.create_foreign_key(None, 'medication', ['medication2_id'], ['id'])
        batch_op.drop_column('med1_id')
        batch_op.drop_column('med2_id')
        batch_op.drop_column('last_checked')

    with op.batch_alter_table('medication_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('scheduled_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('taken_correctly', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('verified_by_camera', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('verification_confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('verification_method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('medication_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('taken_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint(batch_op.f('medication_log_medication_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'medication', ['medication_id'], ['id'])
        batch_op.drop_column('image_path')
        batch_op.drop_column('method')
        batch_op.drop_column('confidence')
        batch_op.drop_column('verified')

    with op.batch_alter_table('snooze_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_medication_time', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('snooze_until', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('snooze_duration_minutes', sa.Integer(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('snooze_log_medication_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('snooze_log_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'medication', ['medication_id'], ['id'])
        batch_op.drop_column('remind_at')
        batch_op.drop_column('snoozed_at')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_chat_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('camera_auto_accept', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'senior'::character varying"))
        batch_op.alter_column('preferences',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint(batch_op.f('user_email_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('user_username_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)
        batch_op.create_unique_constraint(None, ['telegram_chat_id'])
        batch_op.drop_column('is_active')
        batch_op.drop_column('emergency_contact_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emergency_contact_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_role'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.create_unique_constraint(batch_op.f('user_username_key'), ['username'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('user_email_key'), ['email'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('preferences',
               existing_type=sa.Text(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'senior'::character varying"))
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('camera_auto_accept')
        batch_op.drop_column('telegram_chat_id')

    with op.batch_alter_table('snooze_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('snoozed_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('remind_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('snooze_log_user_id_fkey'), 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('snooze_log_medication_id_fkey'), 'medication', ['medication_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('snooze_duration_minutes')
        batch_op.drop_column('created_at')
        batch_op.drop_column('snooze_until')
        batch_op.drop_column('original_medication_time')

    with op.batch_alter_table('medication_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('method', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('image_path', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('medication_log_medication_id_fkey'), 'medication', ['medication_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('taken_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('medication_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('verification_method')
        batch_op.drop_column('verification_confidence')
        batch_op.drop_column('verified_by_camera')
        batch_op.drop_column('taken_correctly')
        batch_op.drop_column('scheduled_time')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('medication_interaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_checked', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('med2_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('med1_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('medication_interaction_med2_id_fkey'), 'medication', ['med2_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('medication_interaction_med1_id_fkey'), 'medication', ['med1_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('severity',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('last_updated')
        batch_op.drop_column('risk_factors')
        batch_op.drop_column('source')
        batch_op.drop_column('recommendation')
        batch_op.drop_column('medication2_id')
        batch_op.drop_column('medication1_id')

    with op.batch_alter_table('medication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pill_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last_taken', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('reminder_times', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('stock_threshold', sa.INTEGER(), server_default=sa.text('5'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('notification_time', postgresql.TIME(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_medication_user_id'))
        batch_op.drop_index(batch_op.f('ix_medication_start_date'))
        batch_op.drop_index(batch_op.f('ix_medication_priority'))
        batch_op.drop_index(batch_op.f('ix_medication_name'))
        batch_op.drop_index(batch_op.f('ix_medication_end_date'))
        batch_op.drop_index(batch_op.f('ix_medication_barcode'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('reference_image_path',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('frequency',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('dosage',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('ai_trained')
        batch_op.drop_column('visual_fingerprint')
        batch_op.drop_column('background_image')
        batch_op.drop_column('reference_images')
        batch_op.drop_column('label_text')
        batch_op.drop_column('image_features')
        batch_op.drop_column('priority')
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('custom_reminder_times')
        batch_op.drop_column('reminder_voice')
        batch_op.drop_column('reminder_sound')
        batch_op.drop_column('reminder_enabled')
        batch_op.drop_column('night')
        batch_op.drop_column('evening')
        batch_op.drop_column('afternoon')
        batch_op.drop_column('morning')

    with op.batch_alter_table('caregiver_senior', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('caregiver_senior_caregiver_id_fkey'), 'user', ['caregiver_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('caregiver_senior_senior_id_fkey'), 'user', ['senior_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('senior_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('caregiver_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('notes')
        batch_op.drop_column('added_at')

    # ### end Alembic commands ###
