"""Add snooze_log table

Revision ID: 8522cfa13530
Revises: 
Create Date: 2025-10-13 21:42:09.646951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8522cfa13530'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snooze_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('medication_id', sa.Integer(), nullable=True),
    sa.Column('original_medication_time', sa.DateTime(), nullable=False),
    sa.Column('snooze_until', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('snooze_duration_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['medication_id'], ['medication.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('caregiver_senior')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caregiver_senior',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('caregiver_id', sa.INTEGER(), nullable=False),
    sa.Column('senior_id', sa.INTEGER(), nullable=False),
    sa.Column('relationship_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('added_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['caregiver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['senior_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('snooze_log')
    # ### end Alembic commands ###
