"""Add medication interaction tables

Revision ID: add_medication_interaction_tables
Revises: 8522cfa13530
Create Date: 2025-10-13 22:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_medication_interaction_tables'
down_revision = '8522cfa13530'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medication_interaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medication1_id', sa.Integer(), nullable=False),
    sa.Column('medication2_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('risk_factors', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['medication1_id'], ['medication.id'], ),
    sa.ForeignKeyConstraint(['medication2_id'], ['medication.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_interaction_id'), 'medication_interaction', ['id'], unique=False)
    op.create_table('interaction_check_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('check_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('medications_checked', sa.Text(), nullable=False),
    sa.Column('interactions_found', sa.Text(), nullable=True),
    sa.Column('overall_risk', sa.String(length=20), nullable=False),
    sa.Column('summary_recommendation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_check_result_id'), 'interaction_check_result', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interaction_check_result_id'), table_name='interaction_check_result')
    op.drop_table('interaction_check_result')
    op.drop_index(op.f('ix_medication_interaction_id'), table_name='medication_interaction')
    op.drop_table('medication_interaction')
    # ### end Alembic commands ###
