"""Add caregiver_senior table

Revision ID: e3a755747043
Revises: add_medication_interaction_tables
Create Date: 2025-11-23 00:11:51.902876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3a755747043'
down_revision = 'add_medication_interaction_tables'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interaction_check_result', schema=None) as batch_op:
        batch_op.drop_index('ix_interaction_check_result_id')

    with op.batch_alter_table('medication_interaction', schema=None) as batch_op:
        batch_op.drop_index('ix_medication_interaction_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medication_interaction', schema=None) as batch_op:
        batch_op.create_index('ix_medication_interaction_id', ['id'], unique=False)

    with op.batch_alter_table('interaction_check_result', schema=None) as batch_op:
        batch_op.create_index('ix_interaction_check_result_id', ['id'], unique=False)

    # ### end Alembic commands ###
