"""Add histogram_fingerprint for Triple-Layer verification

Revision ID: eb2adb14fc62
Revises: 2b9740a37d6e
Create Date: 2026-01-28 20:03:14.069529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb2adb14fc62'
down_revision = '2b9740a37d6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('histogram_fingerprint', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medication', schema=None) as batch_op:
        batch_op.drop_column('histogram_fingerprint')

    # ### end Alembic commands ###
