"""Add refill tracking columns and table

Revision ID: fcc916cd2385
Revises: eb2adb14fc62
Create Date: 2026-02-14 18:53:17.487500

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fcc916cd2385'
down_revision = 'eb2adb14fc62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refill_alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('medication_id', sa.Integer(), nullable=False),
    sa.Column('alert_level', sa.String(length=20), nullable=False),
    sa.Column('days_remaining', sa.Integer(), nullable=False),
    sa.Column('predicted_depletion_date', sa.Date(), nullable=False),
    sa.Column('forecast_method', sa.String(length=20), nullable=True),
    sa.Column('confidence_low', sa.Date(), nullable=True),
    sa.Column('confidence_high', sa.Date(), nullable=True),
    sa.Column('avg_daily_consumption', sa.Float(), nullable=True),
    sa.Column('consumption_variance', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True),
    sa.Column('auto_resolved', sa.Boolean(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['medication_id'], ['medication.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refill_alert', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refill_alert_acknowledged'), ['acknowledged'], unique=False)
        batch_op.create_index(batch_op.f('ix_refill_alert_alert_level'), ['alert_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_refill_alert_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_refill_alert_medication_id'), ['medication_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refill_alert_patient_id'), ['patient_id'], unique=False)

    with op.batch_alter_table('caregiver_senior', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_caregiver_senior_caregiver_id'))
        batch_op.drop_index(batch_op.f('idx_caregiver_senior_senior_id'))

    with op.batch_alter_table('medication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity_remaining', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('initial_quantity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('refill_threshold_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_refill_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('is_prn', sa.Boolean(), nullable=True))
        batch_op.drop_index(batch_op.f('idx_medication_next_dose'))
        batch_op.drop_index(batch_op.f('idx_medication_user_active'))
        batch_op.drop_index(batch_op.f('idx_medication_user_id'))
        batch_op.drop_column('next_dose_time')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('medication_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_medication_log_medication_id'))
        batch_op.drop_index(batch_op.f('idx_medication_log_taken_at'))
        batch_op.create_index(batch_op.f('ix_medication_log_status'), ['status'], unique=False)

    with op.batch_alter_table('security_audit', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('snooze_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_snooze_log_medication_id'))
        batch_op.drop_index(batch_op.f('idx_snooze_log_user_id'))
        batch_op.drop_index(batch_op.f('idx_snooze_remind_at'))
        batch_op.drop_column('remind_at')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_user_email'))
        batch_op.drop_index(batch_op.f('idx_user_username'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_user_username'), ['username'], unique=False)
        batch_op.create_index(batch_op.f('idx_user_email'), ['email'], unique=False)

    with op.batch_alter_table('snooze_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remind_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('idx_snooze_remind_at'), ['user_id', 'remind_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_snooze_log_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_snooze_log_medication_id'), ['medication_id'], unique=False)

    with op.batch_alter_table('security_audit', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('medication_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medication_log_status'))
        batch_op.create_index(batch_op.f('idx_medication_log_taken_at'), [sa.literal_column('taken_at DESC')], unique=False)
        batch_op.create_index(batch_op.f('idx_medication_log_medication_id'), ['medication_id'], unique=False)

    with op.batch_alter_table('medication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('next_dose_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('idx_medication_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_medication_user_active'), ['user_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('idx_medication_next_dose'), ['user_id', 'next_dose_time'], unique=False)
        batch_op.drop_column('is_prn')
        batch_op.drop_column('last_refill_date')
        batch_op.drop_column('refill_threshold_days')
        batch_op.drop_column('initial_quantity')
        batch_op.drop_column('quantity_remaining')

    with op.batch_alter_table('caregiver_senior', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_caregiver_senior_senior_id'), ['senior_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_caregiver_senior_caregiver_id'), ['caregiver_id'], unique=False)

    with op.batch_alter_table('refill_alert', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refill_alert_patient_id'))
        batch_op.drop_index(batch_op.f('ix_refill_alert_medication_id'))
        batch_op.drop_index(batch_op.f('ix_refill_alert_created_at'))
        batch_op.drop_index(batch_op.f('ix_refill_alert_alert_level'))
        batch_op.drop_index(batch_op.f('ix_refill_alert_acknowledged'))

    op.drop_table('refill_alert')
    # ### end Alembic commands ###
