# app/routes/print_schedule.py
"""
Print Medication Schedule and QR Code Medical Card
Generates PDFs and QR codes for easy medication reference
"""
from flask import Blueprint, render_template, send_file, jsonify, url_for, request
from flask_login import login_required, current_user
from io import BytesIO
from datetime import datetime
import json

print_schedule = Blueprint('print_schedule', __name__)

@print_schedule.route('/')
@login_required
def schedule_page():
    """Print schedule page"""
    return render_template('print_schedule/index.html')

@print_schedule.route('/pdf')
@login_required
def generate_pdf():
    """Generate printable PDF medication schedule"""
    try:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import inch
        from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
        from app.models.medication import Medication
        
        medications = Medication.query.filter_by(user_id=current_user.id).all()
        
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=0.5*inch, bottomMargin=0.5*inch)
        
        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            'Title',
            parent=styles['Heading1'],
            fontSize=24,
            spaceAfter=20,
            alignment=1  # Center
        )
        
        elements = []
        
        # Title
        elements.append(Paragraph("💊 My Medication Schedule", title_style))
        elements.append(Paragraph(f"<b>{current_user.username}</b> | Generated: {datetime.now().strftime('%d %B %Y')}", 
                                  ParagraphStyle('Subtitle', alignment=1, fontSize=12, spaceAfter=30)))
        
        # Schedule table
        data = [['Time', 'Medication', 'Dosage', 'Instructions']]
        
        # Group medications by time
        schedule = {
            '🌅 Morning (8:00 AM)': [],
            '☀️ Afternoon (12:00 PM)': [],
            '🌆 Evening (6:00 PM)': [],
            '🌙 Night (9:00 PM)': []
        }
        
        for med in medications:
            if med.morning:
                schedule['🌅 Morning (8:00 AM)'].append(med)
            if med.afternoon:
                schedule['☀️ Afternoon (12:00 PM)'].append(med)
            if med.evening:
                schedule['🌆 Evening (6:00 PM)'].append(med)
            if med.night:
                schedule['🌙 Night (9:00 PM)'].append(med)
        
        for time_slot, meds in schedule.items():
            if meds:
                for i, med in enumerate(meds):
                    data.append([
                        time_slot if i == 0 else '',
                        med.name,
                        med.dosage or '-',
                        (med.instructions or '-')[:50]
                    ])
        
        if len(data) == 1:
            data.append(['', 'No medications scheduled', '', ''])
        
        table = Table(data, colWidths=[2*inch, 2*inch, 1.2*inch, 2*inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#667eea')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 12),
            ('FONTSIZE', (0, 1), (-1, -1), 11),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('TOPPADDING', (0, 1), (-1, -1), 8),
            ('BOTTOMPADDING', (0, 1), (-1, -1), 8),
            ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#f8f9fa')),
            ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#dee2e6'))
        ]))
        
        elements.append(table)
        elements.append(Spacer(1, 30))
        
        # Footer
        footer_style = ParagraphStyle('Footer', fontSize=10, alignment=1, textColor=colors.gray)
        elements.append(Paragraph("📌 Stick this on your refrigerator or keep it by your bedside", footer_style))
        elements.append(Paragraph("Generated by MedGuardian - Your Smart Medication Manager", footer_style))
        
        doc.build(elements)
        buffer.seek(0)
        
        return send_file(
            buffer,
            mimetype='application/pdf',
            as_attachment=True,
            download_name=f'medication_schedule_{datetime.now().strftime("%Y%m%d")}.pdf'
        )
        
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@print_schedule.route('/qr-code')
@login_required
def generate_qr():
    """Generate QR code with medication info"""
    try:
        import qrcode
        from PIL import Image
        from app.models.medication import Medication
        
        medications = Medication.query.filter_by(user_id=current_user.id).all()
        
        # Create data for QR code
        med_data = {
            'patient': current_user.username,
            'generated': datetime.now().isoformat(),
            'medications': [
                {
                    'name': med.name,
                    'dosage': med.dosage,
                    'schedule': {
                        'morning': med.morning,
                        'afternoon': med.afternoon,
                        'evening': med.evening,
                        'night': med.night
                    }
                } for med in medications
            ]
        }
        
        # For QR code, create a short URL or encode essential data
        # We'll encode a compact version
        compact_data = f"MedGuardian|{current_user.username}|"
        compact_data += "|".join([f"{m.name}:{m.dosage}" for m in medications[:10]])  # Limit to 10 for QR size
        
        qr = qrcode.QRCode(
            version=1,
            error_correction=qrcode.constants.ERROR_CORRECT_L,
            box_size=10,
            border=4,
        )
        qr.add_data(compact_data)
        qr.make(fit=True)
        
        img = qr.make_image(fill_color="black", back_color="white")
        
        buffer = BytesIO()
        img.save(buffer, format='PNG')
        buffer.seek(0)
        
        return send_file(
            buffer,
            mimetype='image/png',
            as_attachment=False
        )
        
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@print_schedule.route('/medical-card')
@login_required
def medical_card():
    """Generate printable medical card with QR code"""
    try:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.units import inch
        from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from app.models.medication import Medication
        import qrcode
        
        medications = Medication.query.filter_by(user_id=current_user.id).all()
        
        # Generate QR code
        compact_data = f"MedGuardian|{current_user.username}|"
        compact_data += "|".join([f"{m.name}:{m.dosage}" for m in medications[:10]])
        
        qr = qrcode.QRCode(version=1, box_size=8, border=2)
        qr.add_data(compact_data)
        qr.make(fit=True)
        qr_img = qr.make_image(fill_color="black", back_color="white")
        
        qr_buffer = BytesIO()
        qr_img.save(qr_buffer, format='PNG')
        qr_buffer.seek(0)
        
        # Create PDF
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4)
        
        styles = getSampleStyleSheet()
        elements = []
        
        # Card title
        title_style = ParagraphStyle('CardTitle', fontSize=20, alignment=1, spaceAfter=10)
        elements.append(Paragraph("🏥 Medical ID Card", title_style))
        elements.append(Paragraph(f"<b>{current_user.username}</b>", 
                                  ParagraphStyle('Name', fontSize=16, alignment=1, spaceAfter=20)))
        
        # QR Code
        qr_image = Image(qr_buffer, width=2*inch, height=2*inch)
        elements.append(qr_image)
        elements.append(Spacer(1, 10))
        elements.append(Paragraph("Scan for complete medication list", 
                                  ParagraphStyle('Scan', fontSize=10, alignment=1, textColor=colors.gray)))
        elements.append(Spacer(1, 20))
        
        # Medications list
        elements.append(Paragraph("<b>Current Medications:</b>", styles['Heading3']))
        for med in medications:
            elements.append(Paragraph(f"• {med.name} - {med.dosage}", styles['Normal']))
        
        elements.append(Spacer(1, 30))
        elements.append(Paragraph(f"Generated: {datetime.now().strftime('%d %B %Y')}", 
                                  ParagraphStyle('Date', fontSize=9, alignment=1, textColor=colors.gray)))
        
        doc.build(elements)
        buffer.seek(0)
        
        return send_file(
            buffer,
            mimetype='application/pdf',
            as_attachment=True,
            download_name=f'medical_card_{datetime.now().strftime("%Y%m%d")}.pdf'
        )
        
    except Exception as e:
        return jsonify({'error': str(e)}), 500
